mysql:
    username: ${FLYWAY_USER:root}
    password: ${FLYWAY_PASS:root}
    schema: ${FLYWAY_DB:catalog}
    url: ${MYSQL_HOST}

server:
    port: 8080
    undertow:
        threads:
            worker: 10
            io: 2

spring:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none
