mysql:
    username: root
    password: root
    schema: catalog
    url: admin-video-catalog-api-mysql:3306

server:
    port: 8080
    undertow:
        threads:
            worker: 10
            io: 2

spring:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none
