version: '3'

services:
    admin-video-catalog-api-mysql:
        image: mysql:8.0.31
        container_name: admin-video-catalog-api-mysql
        ports:
            - "3306:3306"
        volumes:
            - admin_video_catalog_api_msyql:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=catalog
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - admin-video-catalog-api-network

    admin-video-catalog-api:
        container_name: admin-video-catalog-api
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        environment:
            - FLYWAY_DB=catalog
            - FLYWAY_USER=root
            - FLYWAY_PASS=root
            - MYSQL_HOST=admin-video-catalog-api-mysql:3306
        ports:
            - "8080:8080"
        networks:
            - admin-video-catalog-api-network
        depends_on:
            - admin-video-catalog-api-mysql

networks:
    admin-video-catalog-api-network:
        driver: bridge

volumes:
    admin_video_catalog_api_msyql:
        driver: local
